version: '3'

services:
  larafood-app:
    build: .
    ports:
    - "8080:80"
    volumes:
      - ./:/usr/share/nginx
    networks:
      - app-network

  larafood-mysql:
    image: mysql:5.7.22
    command: --innodb-use-native-aio=0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: larafood
      MYSQL_ROOT_PASSWORD: larafood
    networks:
      - app-network
    volumes:
      - .docker/dbdata:/var/lib/mysql

networks:
  app-network:
    driver: bridge
